nelmio_api_doc:
    documentation:
        info:
            title: Cars API
            description: CRUD cars api
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api
